#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate data/data.js from songs.json + technique.json + schedule.json.
Run this after editing any of those source files: python3 data/generate.py
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))

def load(name, default):
    path = os.path.join(HERE, name)
    if not os.path.exists(path):
        return default
    with open(path, encoding='utf-8') as f:
        return json.load(f)

songs = load('songs.json', [])
technique = load('technique.json', {})
schedule = load('schedule.json', [])

data = {"songs": songs, "technique": technique, "schedule": schedule}

out = "/* Auto-generated by data/generate.py — do not hand-edit. Edit songs.json / technique.json / schedule.json instead and re-run generate.py */\n"
out += "window.APP_DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"

with open(os.path.join(HERE, 'data.js'), 'w', encoding='utf-8') as f:
    f.write(out)

print(f"Wrote data.js — {len(songs)} songs, {len(schedule)} schedule weeks")
